# ===============================
# Configuration MySQL
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/ATS?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# (ajoute ton mot de passe MySQL sil y en a un, sinon laisse vide)
# Exemple :
# spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
#  JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# Port de l'application
# ===============================
server.port=8080
